{
 "title": "Test Result",
 "description": "k6 Test Result",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "testid", "query": { "query": "label_values(testid)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   { "name": "url", "query": { "query": "label_values(url)" } }
  ]
 },
 "panels": [
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{testid=~\"$testid\",expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_data_received_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_data_sent_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "k6_vus{testid=~\"$testid\"}",
     "legendFormat": "Active VUs"
    },
    {
     "expr": "sum(rate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "Requests Rate"
    },
    {
     "expr": "avg(sum(rate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval])))",
     "legendFormat": "Failed Requests Rate"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "Response  Time (avg)"
    }
   ]
  },
  {
   "title": "Iteration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(sum(irate(k6_data_received_total{testid=~\"$testid\"}[$__range])))",
     "legendFormat": "Received"
    },
    {
     "expr": "avg(sum(irate(k6_data_sent_total{testid=~\"$testid\"}[$__range])))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Error Code Rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Dropped Iteration ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "k6_checks_rate{testid=~\"$testid\"}"
    }
   ]
  },
  { "title": "Thresholds WIP", "type": "table", "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 } },
  {
   "title": "HTTP ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\"}"
    },
    {
     "expr": "histogram_quantile(0, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__range])))"
    }
   ]
  },
  {
   "title": "HTTP breakdown",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_blocked_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_blocked_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_connecting_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_connecting_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Connecting"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_duration_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Duration"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_receiving_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_receiving_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Receiving"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_sending_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_sending_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Sending"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "TLS Handshaking"
    },
    {
     "expr": "avg(histogram_sum(rate(k6_http_req_waiting_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_waiting_seconds{testid=~\"$testid\", url=~\"$url\",scenario=~\"$scenario\"}[$__range])))",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Scenarios",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds{scenario=~\"$scenario\", expected_response=\"true\", testid=~\"$testid\"}[$__range])))"
    },
    {
     "expr": "sum by(scenario) (max(k6_http_reqs_total{testid=~\"$testid\", scenario=~\"$scenario\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(scenario) (sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) (k6_iterations_total{testid=~\"$testid\",scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) ( k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\",expected_response=\"false\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scenario level metrics $scenario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "repeat": "scenario",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scenarios",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_seconds{scenario=~\"$scenario\", expected_response=\"true\", testid=~\"$testid\"}[$__range])))"
      },
      {
       "expr": "sum by(scenario) (max(k6_http_reqs_total{testid=~\"$testid\", scenario=~\"$scenario\"}))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(scenario) (sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(scenario) (k6_iterations_total{testid=~\"$testid\",scenario=~\"$scenario\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(scenario) ( k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\",expected_response=\"false\"})\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "k6_vus{testid=~\"$testid\"}",
       "legendFormat": "Active VUs"
      },
      {
       "expr": "avg(sum(irate(k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\"}[$__range])))",
       "legendFormat": "Requests Rate"
      },
      {
       "expr": "avg(sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\",scenario=~\"$scenario\"}[$__range])))",
       "legendFormat": "Failed Requests Rate"
      },
      {
       "expr": "avg(histogram_sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\",scenario=~\"$scenario\"}[$__range]))\n/\nhistogram_count(rate(k6_http_req_duration_seconds{testid=~\"$testid\",scenario=~\"$scenario\"}[$__range])))",
       "legendFormat": "Response  Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Example Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counter",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "k6_my_counter_total{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "gouge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "targets": [
      {
       "expr": "k6_my_gauge{testid=~\"$testid\"}"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(k6_my_rate_rate{testid=~\"$testid\"})"
      }
     ]
    },
    {
     "title": "trends wip",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "k6_my_trend_avg{testid=~\"$testid\"}",
       "legendFormat": "avg"
      },
      {
       "expr": "k6_my_trend_max{testid=~\"$testid\"}",
       "legendFormat": "max"
      },
      {
       "expr": "k6_my_trend_med{testid=~\"$testid\"}",
       "legendFormat": "med"
      },
      {
       "expr": "k6_my_trend_min{testid=~\"$testid\"}",
       "legendFormat": "min"
      },
      {
       "expr": "k6_my_trend_p90{testid=~\"$testid\"}",
       "legendFormat": "p90"
      },
      {
       "expr": "k6_my_trend_p95{testid=~\"$testid\"}",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  }
 ]
}