version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.40.0
    volumes:
      - ./config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=remote-write-receiver'
    ports:
      - "9090:9090"
    restart: always
