# my global config
global:
  scrape_interval: 5s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s  # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: 'my-little-prom'
    replica: 'r1'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'avalanche'
    scrape_interval: 5s
    static_configs:
      - targets: ['avalanche:9001']
