apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  labels:
    name: grafana-configmap
data:
  datasource.yml: |-
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        editable: true
        isDefault: true
        url: http://prometheus-service.default.svc.cluster.local:9090 
