apiVersion: v1
kind: Service
metadata:
  labels:
    name: prometheus
  name: prometheus-service
spec:
  ports:
    - name: "9090"
      port: 9090
      protocol: TCP
  selector:
    name: prometheus
