# my global config
global:
  scrape_interval: 5s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s  # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    cluster: 'my-little-prom'
    replica: 'r1'

scrape_configs:
  - job_name: 'vmagent'
    static_configs:
      - targets: ['vmagent:8429']

#  - job_name: 'vmalert'
#    static_configs:
#      - targets: ['vmalert:8880']

  - job_name: 'victoriametrics'
    static_configs:
      - targets: ['victoriametrics:8428']

  - job_name: 'avalanche'
    scrape_interval: 5s
    static_configs:
      - targets: ['avalanche:9001']
